server:
  port: 8367
eureka:
  instance:
    hostname: localhost
  server:  #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    peer-eureka-nodes-update-interval-ms: 1000
    wait-time-in-ms-when-sync-empty: 0
  # 不向注册中心注册自己
  client:
    fetch-registry: false
    register-with-eureka: false
    eureka-server-total-connections: 200
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/